apiVersion: v2
version: 0.0.1
name: traefik-ingress
icon: https://raw.githubusercontent.com/ecoma-io/helm-charts/refs/heads/main/icons/traefik-ingress.png
description: Traefik is a modern HTTP reverse proxy and load balancer made to deploy microservices with ease.
home: https://ecoma-io.github.com/helm-charts
keywords:
  - kubernetes
  - traefik 
  - ingress
  - reverse proxy
  - load balancer
sources:
  - https://github.com/ecoma-io/helm-charts/tree/main/charts/traefik-ingress
maintainers:
  - name: Ecoma
    url: https://ecoma.io
dependencies:
  - name: traefik 
    version: "34.x.x"
    repository: "https://traefik.github.io/charts"