
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ template "seaweedfs.volume.fullname" . }}-controller'
  namespace: {{ include "common.names.namespace" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ template "seaweedfs.volume.fullname" . }}-controller-role'
rules:
  - apiGroups: [""]
    resources: ["configmaps", "nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "watch", "list", "patch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ template "seaweedfs.volume.fullname" . }}-controller-binding'
subjects:
  - kind: ServiceAccount
    name: '{{ template "seaweedfs.volume.fullname" . }}-controller'
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  kind: ClusterRole
  name: '{{ template "seaweedfs.volume.fullname" . }}-controller-role'
  apiGroup: rbac.authorization.k8s.io
