apiVersion: v2
version: 1.0.0
name: descheduler
icon: https://raw.githubusercontent.com/ecoma-io/helm-charts/refs/heads/main/icons/descheduler.jpg
description: Descheduler improves cluster stability by evicting pods that violate scheduling policies or imbalance node resources.
home: https://ecoma-io.github.com/helm-charts
keywords:
  - kubernetes
  - descheduler
  - cluster
  - auto balance
sources:
  - https://github.com/ecoma-io/helm-charts/tree/main/charts/descheduler
maintainers:
  - name: Ecoma
    url: https://ecoma.io
dependencies:
  - name: descheduler
    version: 0.x.x
    repository: https://kubernetes-sigs.github.io/descheduler/