## Default values for Cloudflared

## @section Image parameters
## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
## @param image.imagePullPolicy The logic of image pulling.
##
image:
  repository: cloudflare/cloudflared
  tag: "2025.2.1"
  imagePullPolicy: IfNotPresent

## @section Deployment parameters
## @param replicaCount The number of replicas to deploy.
## @param priorityClassName The priority class name to use for the tunnel.
## @param affinity If specified, the pod's scheduling constraints. Affinity is a group of affinity scheduling rules.
## @param tolerations Tolerates any taint that matches the triple `<key,value,effect>` using the matching operator `<operator>`.
## @param topologySpreadConstraints Control how pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains.
## @param resources If specified, it sets the resource requests and limits for the pod.
## @param livenessProbe config the liveness probe for pod
##
replicaCount: 1
priorityClassName: system-cluster-critical
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: cloudflare-tunnel
          topologyKey: "kubernetes.io/hostname"
topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app: cloudflare-tunnel
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway 
tolerations: []
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:    
    cpu: 400m
    memory: 256Mi


## @param metrics.enabled Enable metrics for prometheus monitoring. The crd monitoring.coreos.com/v1 must be already installed on the target.
## @param metrics.port The port to use for metrics.
metrics:
  enabled: true
  port: 9327

livenessProbe:
  httpGet:
    path: /ready
    port: 9327
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 10  


## @param tunnel.token The connector token provided at the end of the CF Zero Trust tunnel creation.
## @param tunnel.existingSecret The name of the existing secret containing the token. The secret key must be set to 'cf-tunnel-token'.
## @param tunnel.logLevel The log level to use for the tunnel (Accept: debug, info, warn, error )
## @param tunnel.protocol Specifies the protocol used to establish a connection between cloudflared and the Cloudflare global network. Available values are auto, http2, and quic.
## @param tunnel.retries Specifies the maximum number of retries for connection/protocol errors. 
tunnel:
  token: ""
  existingSecret: ""
  logLevel: info
  protocol: http2
  retries: 2


## @param controller.updateStrategy.type Controller deployment update strategy
## @param controller.updateStrategy.rollingUpdate Controller deployment rolling update configuration parameters
##
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1       


## @param pdb.create Enable/disable a Pod Disruption Budget creation
## @param pdb.minAvailable Minimum number/percentage of pods that should remain scheduled
## @param pdb.maxUnavailable Maximum number/percentage of pods that may be made unavailable. Defaults to `1` if both `controller.pdb.minAvailable` and `controller.pdb.maxUnavailable` are empty.
##
pdb:
  create: true
  maxUnavailable: 0
  minAvailable: 1


autoscaler:
  enabled: true  
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70
  targetMemory: 70

