{{- if .Values.defaultClusterIssuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  ca:
    secretName:  {{ .Values.defaultClusterIssuer.secretName }}
{{- end }}