{{- if and .Values.metrics.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: "{{ .Release.Name }}-servicemonitor"
  name: "{{ .Release.Name }}-servicemonitor"
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - targetPort: metrics
      path: /metrics
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}